### PR TITLE
Block on jsonc errors as well as our own Azure errors when editing tags

### PR DESCRIPTION
**Pull request by ejizba**
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/53
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/18

### CODE REVIEW

**Comment by neelip** [comment]
When I am adding to duplicated keys, I do see "Duplicate object key" inline warning but I can still save the document successfully. Is the intention to only prompt inline warning?

**Comment by ejizba** [comment]
Uh hmm interesting - jsonc considers those to be "warnings", not "errors". I added an Azure-specific error to catch it, modeled after the portal:
Screen Shot 2021-02-17 at 5 20 51 PM

**Comment by neelip** [comment]
nit: The jsonc warning is case-sensitive
image
image

**Review by nturinski — APPROVED** [review]

**Comment by ejizba** [comment]
> nit: The jsonc warning is case-sensitive

Correct, I don't control the jsonc warnings/errors. Azure is more strict than jsonc, which is why I created our own error to enforce that

**Pull request merged**
