### PR TITLE
Show workspace resources even if workspace isn't open

### PR DESCRIPTION
**Pull request by alexweininger**
Instead of not displaying resources if no workspace is opened, show resources and also add a tree item that prompts users to open a folder/workspace.

image

This more closely mirrors the current behavior, and fixes https://github.com/microsoft/vscode-azurestorage/issues/1214

### CODE REVIEW

**Comment by nturinski** [comment]
Have we explored other solutions? I thought I remember Phillip suggestion to have a "getting started" view if there were no tree items. For example:

image
image

**Comment by alexweininger** [comment]
> Have we explored other solutions? I thought I remember Phillip suggestion to have a "getting started" view if there were no tree items.

Yes Phillip actually implemented 3 different welcome views for the workspace view. The PR removes the "no workspace" welcome view. The "no workspace resources" and "no workspace resource providers" welcome views remain.

**Review by nturinski — APPROVED** [review]
I think we should consider improving these views with some buttons to get users started, but I won't block for that.

**Comment by alexweininger** [comment]
> I think we should consider improving these views with some buttons to get users started, but I won't block for that.

Yeah, I wasn't quite sure what to put in terms of buttons. It'd be nice to have a button that took them to the extensions view but only showed extensions that contribute workspace resource providers.

**Pull request merged**
